# Generated by Django 5.0.7 on 2024-11-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration): 

    dependencies = [
        ('shop', '0002_staticfiles_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfiles',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'shop'), (2, 'manager')], default=1),
        ),
    ]
