# Generated by Django 5.0.7 on 2024-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration): 

    dependencies = [
        ('shop', '0003_alter_staticfiles_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfiles',
            name='type',
            field=models.CharField(choices=[('shop', 'Shop'), ('manager', 'Manager')], default='shop', max_length=20),
        ),
    ]
