"""
Django settings for manager project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
GOOGLE_SITE_VERIFICATION = ""
GOOGLE_TAG = ""
GOOGLE_ANALYTICS = ""

import os,pymysql,sys
from pathlib import Path
from decouple import config

USER = "dd"
GROUP = "www-data"

pymysql.install_as_MySQLdb()

CACHE_FOLDER = "/var/cache/miracles.site/"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

ADMIN_BASE_URL = 'http://manager.miracles.site'

DOMAIN = 'miracles.site'
HOST = DOMAIN
HOME_DIR = BASE_DIR.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ph2$50f%khtwe-dbv_^cykc+(l7lbeg35e^9qf=#d#@s^gtw7p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = ['manager.miracles.site','t.manager.miracles.site']

BASE_URL = 'miracles.site'

SITE_URL = 'miracles.site'

# Application definition

sys.path.append(str(HOME_DIR / "shop/server"))

INSTALLED_APPS = [
    'manager',
    'checkout',
    'shop',
    'catalog',
    'user',
    'mptt',
    'order',
    'category',
    'rest_framework',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'django_user_agents'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'manager.middleware.locale.LocaleMiddleware',
    'manager.middleware.login.Login',
    'manager.middleware.admin_model.AdminModelMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware'
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[HOME_DIR / 'manager/client/html',
                HOME_DIR / 'manager/client/image',
                CACHE_FOLDER + 'html',
                CACHE_FOLDER + 'static'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'user.context.auth',
                'django.contrib.messages.context_processors.messages',
                'manager.context.extends',
            ],
        },
    },
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
        }
    },
    'backup': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
        }
    }
}
# DATABASE_ROUTERS = ['main.router.DeafultRouter']
DATABASE_OPTIONS = {
    'unix_socket' : '/tmp/mysql.sock',
}
PROTOCOL = 'https'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'uk'
DEFAULT_LANGUAGE_CODE = 'uk'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/
STATIC_ROOT = '/var/cache/miracles.site/manager/static/miracles.site/static/'
STATIC_URL = '/static/'
#AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend','user.backends.AuthByPhone')
AUTH_USER_MODEL = 'user.User'
WATERMARK = HOME_DIR / 'media/watermark.png'


CACHE_DIR = '/var/cache/miracles.site/manager'

MEDIA_ROOT = HOME_DIR / f'media/{DOMAIN}'
MEDIA_URL = f'/media/{DOMAIN}/'

SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default session engine
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Retain session after browser close
SESSION_COOKIE_SECURE = False

DEBUG_TOOLBAR_PATCH_SETTINGS = False
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o777
INTERNAL_IPS = []

MAX_MINIFIED_VERSIONS = 3
STATIC_SOURCE_ROOT = HOME_DIR / 'manager/client/static/'
MINIFIED_ROOT = CACHE_FOLDER + 'manager/static/'
SVG_CACHE_FOLDER = CACHE_FOLDER + "static/image/svg/"

LANGUAGES = (
    ('uk-UA', 'Українська'),
    ('uk', 'Українська'),
    ('ua', 'Українська'),
    ('en', 'English'),
    ('nl', 'Dutch'),
    ('de', 'Deutsch'),
)
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
LANGUAGE_SESSION_KEY = 'lang'
DEFAULT_LANGUAGE_CODE = 'uk'

#dict of possible language keys
AVAIL_LANGUAGES = {
    'ua':'ua',
    'uk-ua':'ua',
    'uk-UA':'ua',
    'ua-UA':'ua',
    'uk':'ua',
    'en':'en',
    'en-US':'en',
    'nl':'nl',
    'de':'de',
    'de-DE':'de'
}

CSS_BUILD = 44
JS_BUILD = 19

NO_IMAGE_PLACEHOLDER = '/media/no_image.jpg'

LIQPAY_PUBLIC = ""
LIQPAY_PRIVATE = ""


BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_TIMEZONE = 'UTC'

from django.utils.translation import gettext_lazy as _

SPRITE_CATEGORIES = True

TIGRES_CATEGORIES = True

PHONES = ["(099) 999-99-99","(066) 666-66-66","(033) 333-33-33","(077) 777-77-77"]

ADDRESS = ""
COMPANY_NAME = ""

AOC = True

PHONE = PHONES[0]

SMS_PASSWORD = ''
SMS_ACCOUNT = ''
SMS_SIGN = ''

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DEFAULT_CURRENCY = "UAH"

#SMTP
EMAIL = 'ffs@gmail.com'
EMAIL_TITLE = ''
EMAIL_HOST = 'gmail.com'
EMAIL_HOST_USER = 'info'
EMAIL_HOST_PASSWORD = _("Portal")
EMAIL_PORT = 25

YOUTUBE_LINK = "https://youtube.com"
FACEBOOK_LINK = "https://facebook.com"
ADDRESS = ""
IOS_APP = ""