from .brand import BrandAdmin
from .category import CategoryAdmin
from .offer import OfferAdmin
from .popular import PopularAdmin
from .product import ProductAdmin,Add_AdminModel
from .special import SpecialAdmin
from .storage import StorageAdmin
from .attribute import AttributeAdmin
from .tag import TagAdmin
from .gallery import GalleryAdmin
from .city import CityAdmin
from .info import InfoAdmin
from .featured import FeaturedAdmin
from .google import GoogleFeedAdmin
from .currency import CurrencyAdmin
from .export import ExportAdmin