# Generated by Django 5.1.6 on 2025-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='Код')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('verified', models.BooleanField(default=0, verbose_name='Email підтверджено')),
                ('name', models.CharField(max_length=255, null=True, verbose_name="Ім'я")),
                ('lname', models.CharField(max_length=255, null=True, verbose_name='Призвище')),
                ('sname', models.CharField(max_length=255, null=True, verbose_name='По батькові')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Номер телефону')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус користувача')),
                ('subscription', models.BooleanField(default=True, verbose_name='Підписати пошту')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Востаннє в мережі')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата реєстрації')),
                ('device_id', models.CharField(max_length=50, null=True, unique=True)),
                ('notifications', models.BooleanField(default=1)),
                ('fcm_token', models.CharField(max_length=255, null=True)),
                ('update_departaments', models.BooleanField(default=False)),
                ('social_type', models.PositiveIntegerField(choices=[(1, 'fb'), (2, 'g')], null=True)),
                ('social_id', models.CharField(max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувачи',
                'verbose_name_plural': 'Користувачи',
            },
        ),
    ]
