from .filter import FilterView
from .category import CategoryView
from .brand import BrandView
from .product import ProductView
from .tag import TagView
from .latest import NewView
from .special import SaleView
from .bestsellers import BestsellersView
from .search import search
from .quick_view import Quick_View
from .pricelist import PriceList
from .feedback import FeedbackView
from .brands import BrandsView
from .rating import rating