# Generated by Django 5.1.6 on 2025-03-10 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_meta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.PositiveIntegerField()),
                ('to', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('database', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('model', models.CharField(max_length=50, verbose_name='Артикул')),
                ('active', models.BooleanField(default=1, verbose_name='Актив.')),
            ],
            options={
                'verbose_name': 'Нові товари',
                'verbose_name_plural': 'Нові товари',
                'ordering': ['-active'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'В обробці'), (2, 'Виконано')], default=2)),
                ('link', models.CharField(max_length=100, null=True)),
                ('function', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.BooleanField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('export', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.export')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_status', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'export')},
            },
        ),
        migrations.CreateModel(
            name='ExportMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('json_text', models.TextField(null=True)),
                ('export', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='manager.exportstatus')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(verbose_name='Процентна націнка')),
                ('additional', models.PositiveIntegerField(default=0, null=True)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.price')),
            ],
        ),
        migrations.AddField(
            model_name='export',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.task'),
        ),
    ]
