# Generated by Django 5.1.6 on 2025-05-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='PriceFrmTo',
        ),
    ]
