# Generated by Django 5.1.6 on 2025-06-12 07:45

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='Article')),
                ('retail_price', models.FloatField(default=0, verbose_name='Price')),
                ('wholesale_price', models.FloatField(default=0, verbose_name='Wholesale Price')),
                ('purchase_price', models.FloatField(default=0, verbose_name='Purchase price')),
                ('length', models.CharField(max_length=50, null=True, verbose_name='Lenght')),
                ('width', models.CharField(max_length=50, null=True, verbose_name='Width')),
                ('height', models.CharField(max_length=50, null=True, verbose_name='Height')),
                ('is_available', models.BooleanField(default=0, verbose_name='Is available')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('price_fixed', models.BooleanField(default=0, verbose_name='Fixed price')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('qty', models.FloatField(default=0)),
                ('counter', models.CharField(default='cnt.', max_length=10)),
                ('is_top', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_available', '-last_modified', '-is_top'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tag/', verbose_name='Картинка')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='BrandDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(max_length=20000, null=True, verbose_name='Опис')),
                ('json_text', models.TextField(max_length=20000, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.language')),
            ],
            options={
                'db_table': 'brand_description',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Країна виробник')),
                ('active', models.BooleanField(default=False, verbose_name='Зробити сторінкою?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Зображення')),
                ('description', models.ManyToManyField(related_name='obj', to='catalog.branddescription')),
            ],
            options={
                'verbose_name': 'Виробники',
                'verbose_name_plural': 'Виробники',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='Картинка')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=1, verbose_name='Активна')),
                ('bgcolor', models.CharField(max_length=20, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='catalog.category', verbose_name='Батьківська')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('category', models.ManyToManyField(related_name='attributes', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Атрибут',
            },
        ),
        migrations.CreateModel(
            name='Category_Thumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(max_length=20000, null=True, verbose_name='Опис')),
                ('json_text', models.TextField(max_length=20000, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.language')),
            ],
            options={
                'db_table': 'category_description',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.categorydescription'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рекомендовані',
                'verbose_name_plural': 'Рекомендовані',
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Популярні',
                'verbose_name_plural': 'Популярні',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.product', verbose_name='Товар')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Спец.Ціна')),
                ('percent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Акції',
                'verbose_name_plural': 'Акції',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalog.brand', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Featured products'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='products/%Y/%m/%d', verbose_name='Картинка')),
                ('position', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядоковий номер')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('text', models.CharField(max_length=1500, verbose_name='Текст')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.feedback', verbose_name='Родитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('products', models.ManyToManyField(related_name='related', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Комплектуючі',
            },
        ),
        migrations.CreateModel(
            name='Add_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Additional Article')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_model', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Additional Article',
                'verbose_name_plural': 'Additional Articles',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(max_length=20000, null=True, verbose_name='Опис')),
                ('json_text', models.TextField(max_length=20000, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.language')),
            ],
            options={
                'db_table': 'product_description',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.productdescription'),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.language')),
            ],
        ),
        migrations.AddField(
            model_name='productdescription',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.storage', verbose_name='Storage'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='catalog.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TagDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(max_length=20000, null=True, verbose_name='Опис')),
                ('json_text', models.TextField(max_length=20000, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.language')),
            ],
            options={
                'db_table': 'tag_description',
                'unique_together': {('language', 'meta_description'), ('language', 'name'), ('language', 'title')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.ManyToManyField(related_name='obj', to='catalog.tagdescription'),
        ),
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb', to='catalog.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute')),
            ],
            options={
                'verbose_name': 'Значення',
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='products', to='catalog.value', verbose_name='Attributes'),
        ),
    ]
